ecommerce/coupons/urls.py
from django.conf.urls import url

from ecommerce.coupons import views

urlpatterns = [
    url(r'^offer/$', views.CouponOfferView.as_view(), name='offer'),
    url(r'^redeem/$', views.CouponRedeemView.as_view(), name='redeem'),
    url(
        r'^enrollment_code_csv/(?P<number>[-\w]+)/$',
        views.EnrollmentCodeCsvView.as_view(),
        name='enrollment_code_csv'
    ),
    url(r'^(.*)$', views.CouponAppView.as_view(), name='app'),
]

ecommerce/courses/urls.py
from django.conf.urls import url

from ecommerce.courses import views

urlpatterns = [
    url(r'^migrate/$', views.CourseMigrationView.as_view(), name='migrate'),
    url(r'^convert_course/$', views.ConvertCourseView.as_view(), name='convert_course'),

    # Declare all paths above this line to avoid dropping into the Course Admin Tool (which does its own routing)
    url(r'^(.*)$', views.CourseAppView.as_view(), name='app'),
]

ecommerce/credit/urls.py
from django.conf.urls import url

from ecommerce.core.constants import COURSE_ID_PATTERN
from ecommerce.credit.views import Checkout

urlpatterns = [
    url(r'^checkout/{course}/$'.format(course=COURSE_ID_PATTERN),
        Checkout.as_view(), name='checkout'),
]

ecommerce/urls.py
import os

from auth_backends.urls import auth_urlpatterns
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.views.defaults import page_not_found, server_error
from django.views.generic import TemplateView
from django.views.i18n import javascript_catalog

from ecommerce.core import views as core_views
from ecommerce.core.url_utils import get_lms_dashboard_url
from ecommerce.core.views import LogoutView
from ecommerce.extensions.urls import urlpatterns as extensions_patterns


def handler403(_):
    """Redirect unauthorized users to the LMS student dashboard.

    Removing URLs isn't the most elegant way to hide Oscar's front-end from
    public view. It would require revising templates and parts of the Oscar core
    which assume that these URLs exist. However, a clean way to, in effect,
    disable these URLs is to only make them available to users with staff
    permissions, the same protection used to guard the management dashboard from
    public access.

    This minimally invasive approach allows us to protect Oscar's front-end
    without sacrificing any internal functionality. Users not authorized to view
    Oscar's front-end are redirected to the LMS student dashboard, as one would
    usually be after signing into the LMS.
    """
    return redirect(get_lms_dashboard_url())


admin.autodiscover()

js_info_dict = {
    'packages': ('courses',),
}

# NOTE 1: Add our logout override first to ensure it is registered by Django as the actual logout view.
# NOTE 2: These same patterns are used for rest_framework's browseable API authentication links.
AUTH_URLS = [url(r'^logout/$', LogoutView.as_view(), name='logout'), ] + auth_urlpatterns

urlpatterns = AUTH_URLS + [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^auto_auth/$', core_views.AutoAuth.as_view(), name='auto_auth'),
    url(r'^api-auth/', include(AUTH_URLS, namespace='rest_framework')),
    url(r'^api-docs/', include('rest_framework_swagger.urls')),
    url(r'^courses/', include('ecommerce.courses.urls', namespace='courses')),
    url(r'^credit/', include('ecommerce.credit.urls', namespace='credit')),
    url(r'^coupons/', include('ecommerce.coupons.urls', namespace='coupons')),
    url(r'^health/$', core_views.health, name='health'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict, name='javascript-catalog'),
]

# Install Oscar extension URLs
urlpatterns += extensions_patterns

robots = TemplateView.as_view(template_name='robots.txt', content_type='text/plain')
urlpatterns += [
    url(r'^robots\.txt$', robots, name='robots')
]

if settings.DEBUG and settings.MEDIA_ROOT:  # pragma: no cover
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

if settings.DEBUG:  # pragma: no cover
    urlpatterns += [
        url(r'^403/$', handler403, name='403'),
        url(r'^404/$', page_not_found, name='404'),
        url(r'^500/$', server_error, name='500'),
        url(r'^bootstrap/$', TemplateView.as_view(template_name='bootstrap-demo.html')),
    ]
    # Allow error pages to be tested

    if os.environ.get('ENABLE_DJANGO_TOOLBAR', False):
        import debug_toolbar  # pylint: disable=import-error, wrong-import-position,wrong-import-order

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls))
        ]

ecommerce/core/models.py
import datetime
import hashlib
import logging
from urlparse import urljoin

from analytics import Client as SegmentClient
from dateutil.parser import parse
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.contrib.sites.models import Site
from django.core.cache import cache
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.functional import cached_property
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _
from edx_rest_api_client.client import EdxRestApiClient
from jsonfield.fields import JSONField
from requests.exceptions import ConnectionError, Timeout
from slumber.exceptions import HttpNotFoundError, SlumberBaseException

from ecommerce.core.url_utils import get_lms_url
from ecommerce.core.utils import log_message_and_raise_validation_error
from ecommerce.courses.utils import mode_for_seat
from ecommerce.extensions.payment.exceptions import ProcessorNotFoundError
from ecommerce.extensions.payment.helpers import get_processor_class, get_processor_class_by_name

log = logging.getLogger(__name__)


class SiteConfiguration(models.Model):
    """Custom Site model for custom sites/microsites.

    This model will enable the basic theming and payment processor
    configuration for each custom site.
    The multi-tenant implementation has one site per partner.
    """

    site = models.OneToOneField('sites.Site', null=False, blank=False, on_delete=models.CASCADE)
    partner = models.ForeignKey('partner.Partner', null=False, blank=False, on_delete=models.CASCADE)
    lms_url_root = models.URLField(
        verbose_name=_('LMS base url for custom site/microsite'),
        help_text=_("Root URL of this site's LMS (e.g. https://courses.stage.edx.org)"),
        null=False,
        blank=False
    )
    theme_scss_path = models.CharField(
        verbose_name=_('Path to custom site theme'),
        help_text=_('Path to scss files of the custom site theme'),
        max_length=255,
        null=False,
        blank=False
    )
    payment_processors = models.CharField(
        verbose_name=_('Payment processors'),
        help_text=_("Comma-separated list of processor names: 'cybersource,paypal'"),
        max_length=255,
        null=False,
        blank=False
    )
    client_side_payment_processor = models.CharField(
        verbose_name=_('Client-side payment processor'),
        help_text=_('Processor that will be used for client-side payments'),
        max_length=255,
        null=True,
        blank=True
    )
    oauth_settings = JSONField(
        verbose_name=_('OAuth settings'),
        help_text=_('JSON string containing OAuth backend settings.'),
        null=False,
        blank=False,
        default={}
    )
    segment_key = models.CharField(
        verbose_name=_('Segment key'),
        help_text=_('Segment write/API key.'),
        max_length=255,
        null=True,
        blank=True
    )
    from_email = models.CharField(
        verbose_name=_('From email'),
        help_text=_('Address from which emails are sent.'),
        max_length=255,
        null=True,
        blank=True
    )
    enable_enrollment_codes = models.BooleanField(
        verbose_name=_('Enable enrollment codes'),
        help_text=_('Enable the creation of enrollment codes.'),
        blank=True,
        default=False
    )
    payment_support_email = models.CharField(
        verbose_name=_('Payment support email'),
        help_text=_('Contact email for payment support issues.'),
        max_length=255,
        blank=True,
        default="support@example.com"
    )
    payment_support_url = models.CharField(
        verbose_name=_('Payment support url'),
        help_text=_('URL for payment support issues.'),
        max_length=255,
        blank=True
    )
    utm_cookie_name = models.CharField(
        verbose_name=_('UTM Cookie Name'),
        help_text=_('Name of cookie storing UTM data.'),
        max_length=255,
        blank=True,
        default="",
    )
    affiliate_cookie_name = models.CharField(
        verbose_name=_('Affiliate Cookie Name'),
        help_text=_('Name of cookie storing affiliate data.'),
        max_length=255,
        blank=True,
        default="",
    )
    enable_otto_receipt_page = models.BooleanField(
        verbose_name=_('Enable Otto receipt page'),
        help_text=_('Enable the usage of Otto receipt page.'),
        blank=True,
        default=False
    )
    send_refund_notifications = models.BooleanField(
        verbose_name=_('Send refund email notification'),
        blank=True,
        default=False
    )
    enable_sdn_check = models.BooleanField(
        verbose_name=_('Enable SDN check'),
        help_text=_('Enable SDN check at checkout.'),
        default=False
    )
    sdn_api_url = models.CharField(
        verbose_name=_('US Treasury SDN API URL'),
        max_length=255,
        blank=True
    )
    sdn_api_key = models.CharField(
        verbose_name=_('US Treasury SDN API key'),
        max_length=255,
        blank=True
    )
    sdn_api_list = models.CharField(
        verbose_name=_('SDN lists'),
        help_text=_('A comma-separated list of Treasury OFAC lists to check against.'),
        max_length=255,
        blank=True
    )

    class Meta(object):
        unique_together = ('site', 'partner')

    @property
    def payment_processors_set(self):
        """
        Returns a set of enabled payment processor keys
        Returns:
            set[string]: Returns a set of enabled payment processor keys
        """
        return {raw_processor_value.strip() for raw_processor_value in self.payment_processors.split(',')}

    def _clean_payment_processors(self):
        """
        Validates payment_processors field value

        Raises:
            ValidationError: If `payment_processors` field contains invalid/unknown payment_processor names
        """
        value = self.payment_processors.strip()
        if not value:
            raise ValidationError('Invalid payment processors field: must not consist only of whitespace characters')

        processor_names = value.split(',')
        for name in processor_names:
            try:
                get_processor_class_by_name(name.strip())
            except ProcessorNotFoundError as exc:
                log.exception(
                    "Exception validating site configuration for site `%s` - payment processor %s could not be found",
                    self.site.id,
                    name
                )
                raise ValidationError(exc.message)

    def _clean_client_side_payment_processor(self):
        """
        Validates the client_side_payment_processor field value.


        Raises:
            ValidationError: If the field contains the name of a payment processor NOT found in the
            payment_processors field list.
        """
        value = (self.client_side_payment_processor or '').strip()
        if value and value not in self.payment_processors_set:
            raise ValidationError('Processor [{processor}] must be in the payment_processors field in order to '
                                  'be configured as a client-side processor.'.format(processor=value))

    def _all_payment_processors(self):
        """ Returns all processor classes declared in settings. """
        all_processors = [get_processor_class(path) for path in settings.PAYMENT_PROCESSORS]
        return all_processors

    def get_payment_processors(self):
        """
        Returns payment processor classes enabled for the corresponding Site

        Returns:
            list[BasePaymentProcessor]: Returns payment processor classes enabled for the corresponding Site
        """
        all_processors = self._all_payment_processors()
        all_processor_names = {processor.NAME for processor in all_processors}

        missing_processor_configurations = self.payment_processors_set - all_processor_names
        if missing_processor_configurations:
            processor_config_repr = ", ".join(missing_processor_configurations)
            log.warning(
                'Unknown payment processors [%s] are configured for site %s', processor_config_repr, self.site.id
            )

        return [
            processor for processor in all_processors
            if processor.NAME in self.payment_processors_set and processor.is_enabled()
        ]

    def get_client_side_payment_processor_class(self):
        """ Returns the payment processor class to be used for client-side payments.

        If no processor is set, returns None.

         Returns:
             BasePaymentProcessor
        """
        if self.client_side_payment_processor:
            for processor in self._all_payment_processors():
                if processor.NAME == self.client_side_payment_processor:
                    return processor

        return None

    def get_from_email(self):
        """
        Returns the configured from_email value for the specified site.  If no from_email is
        available we return the base OSCAR_FROM_EMAIL setting

        Returns:
            string: Returns sender address for use in customer emails/alerts
        """
        return self.from_email or settings.OSCAR_FROM_EMAIL

    @cached_property
    def segment_client(self):
        return SegmentClient(self.segment_key, debug=settings.DEBUG)

    def save(self, *args, **kwargs):
        # Clear Site cache upon SiteConfiguration changed
        Site.objects.clear_cache()
        super(SiteConfiguration, self).save(*args, **kwargs)

    def build_ecommerce_url(self, path=''):
        """
        Returns path joined with the appropriate ecommerce URL root for the current site.

        Returns:
            str
        """
        scheme = 'http' if settings.DEBUG else 'https'
        ecommerce_url_root = "{scheme}://{domain}".format(scheme=scheme, domain=self.site.domain)

ecommerce/extensions/analytics/models.py
from oscar.apps.analytics.models import *  # pragma: no cover pylint: disable=wildcard-import,unused-wildcard-import

ecommerce/extensions/checkout/models.py
# noinspection PyUnresolvedReferences
# pylint: disable=wildcard-import
from oscar.apps.checkout.models import *  # pragma: no cover

ecommerce/extensions/customer/models.py
# noinspection PyUnresolvedReferences
from oscar.apps.customer.models import *  # pragma: no cover noqa pylint: disable=wildcard-import,unused-wildcard-import

ecommerce/extensions/dashboard/models.py
# noinspection PyUnresolvedReferences
from oscar.apps.dashboard.models import *  # pragma: no cover noqa pylint: disable=wildcard-import,unused-wildcard-import

ecommerce/extensions/dashboard/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _


class UserFormMixin(forms.Form):
    """ Mixin for user field filtering. """
    username = forms.CharField(required=False, label=_("Username"))
    email = forms.CharField(required=False, label=_("Email"))

ecommerce/extensions/dashboard/orders/forms.py
from oscar.apps.dashboard.orders.forms import OrderSearchForm as CoreOrderSearchForm

from ecommerce.extensions.dashboard.forms import UserFormMixin


class OrderSearchForm(UserFormMixin, CoreOrderSearchForm):
    pass

ecommerce/extensions/dashboard/refunds/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from oscar.core.loading import get_model

from ecommerce.extensions.dashboard.forms import UserFormMixin
from ecommerce.extensions.refund.status import REFUND

Refund = get_model('refund', 'Refund')
status_choices = tuple([(status, status) for status in Refund.all_statuses()])


class RefundSearchForm(UserFormMixin, forms.Form):
    id = forms.IntegerField(required=False, label=_('Refund ID'))
    status = forms.MultipleChoiceField(choices=status_choices, label=_('Status'), required=False)

    def clean(self):
        cleaned_data = super(RefundSearchForm, self).clean()

        if not cleaned_data.get('status'):
            # If no statuses are specified, default to displaying all those refunds requiring action.
            cleaned_data['status'] = list(set(Refund.all_statuses()) - set((REFUND.COMPLETE, REFUND.DENIED)))

ecommerce/templates/courses/course_app.html
{% extends 'edx/base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block title %}{% trans "Courses" %}{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{% static 'bower_components/pikaday/css/pikaday.css' %}"
          type="text/x-scss">
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-default" aria-label="Account">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#main-navbar-collapse" aria-expanded="false">
                    <span class="sr-only">{% trans "Toggle navigation" %}</span>
                    <span aria-hidden="true" class="icon-bar"></span>
                    <span aria-hidden="true" class="icon-bar"></span>
                    <span aria-hidden="true" class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/courses/">
                    <img class="navbar-brand-logo" alt="{{ platform_name }} logo" src="{% static 'images/default-logo.png' %}"/>
                    <div class="navbar-brand-app">{% trans "E-Commerce Administration" %}</div>
                </a>
            </div>

            <div class="collapse navbar-collapse" id="main-navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li class="btn-group user-menu">
                            <button type="button" class="btn btn-default hidden-xs main-btn nav-button"
                                    onclick="window.open('{{ lms_dashboard_url }}');">
                                <i class="icon fa fa-home" aria-hidden="true"></i>
                                <span class="sr-only">{% trans "Dashboard for:" %}</span>
                                {{ user.username }}
                            </button>
                            <button type="button" class="btn btn-default dropdown-toggle hidden-xs nav-button"
                                    data-toggle="dropdown"
                                    aria-haspopup="true">
                                <span class="caret"></span>
                                <span class="sr-only">{% trans "Toggle Dropdown" %}</span>
                            </button>
                            <ul class="dropdown-menu" aria-expanded="false">
                                {% include "courses/menu_options.html" %}
                            </ul>
                            {% include "courses/menu_options.html" with additional_class="visible-xs" %}
                        </li>
                    {% else %}
                        <a class="btn btn-primary navbar-btn hidden-xs" href="{% url 'login' %}">{% trans "Login" %}</a>
                        <li class="visible-xs"><a class="nav-link" href="{% url 'login' %}">{% trans "Login" %}</a></li>
                        </a>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% include "edx/partials/_administration_menu.html" %}
{% endblock navbar %}

{% block content %}
    <div id="app" class="container" data-credit-providers="{{ credit_providers }}"></div>
    <script>
        window.bulkEnrollmentCodesEnabled = {% if bulk_enrollment_codes_enabled %}true{% else %}false{% endif %};
    </script>
{% endblock %}

{% block footer %}
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 text-right">
                    <em>{% blocktrans %}{{ platform_name }} Course Administration Tool{% endblocktrans %}</em>
                </div>
            </div>
        </div>
    </footer>
{% endblock footer %}

{% block javascript %}
    <script src="{% static 'js/apps/course_admin_app.js' %}"></script>
{% endblock %}

ecommerce/templates/courses/menu_options.html
{% extends 'edx/base_menu.html' %}
{% load core_extras %}
{% load i18n %}


{% block additional_options %}
    <li class="{{ additional_class }}">
        <a class="nav-link" href="{{ lms_dashboard_url }}">{% trans "Student Dashboard" %}</a>
    </li>
    <li class="{{ additional_class }}">
        <a class="nav-link" href="{% url 'courses:app' '' %}">{% trans "Course Admin Tool" %}</a>
    </li>
    <li class="{{ additional_class }}"
        ><a class="nav-link" href="{% url 'dashboard:index' %}">{% trans "E-Commerce Dashboard" %}</a>
    </li>
    <li class="divider {{ additional_class }}"></li>
{% endblock additional_options %}